services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gateway-service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5431:5432'
