services:
  gateway-service-db:
    image: 'postgres:latest'
    container_name: 'gateway-service-db'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  image: 'eureka-service:latest'
#  container_name: 'eureka-service'
#  ports:
#    - '8761:8761'
