spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
          - Path=/is/api/**
        filters:
          - RewritePath=/inventory-service/(?<segment>.*), /${segment}
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/os/api/v1/orders
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true
  info:
    git:
      mode: full
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
