spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
          - Path=/inventory/**
#        filters:
#          - RewritePath=/inventory-service/(?<segment>.*), /${segment}
#      - id: order-service
#        uri: lb://order-service
#        predicates:
#          - Path=/order-service/**
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_service?serverTimezone=America/Chicago&createDatabaseIfNotExist=true&useLegacyDatatimeCode=false
    username: root
    password: admin
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
#  servlet:
#    context-path: /gateway/api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Spring Actuator Configurations
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
