spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5431/ecommerce
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework.web: info
