spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5431/order-_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    open-in-view: false

server:
  port: 8081
  servlet:
    context-path: /os/api

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework.web: info
