spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost/inventory_service
    username: myuser
    password: secret

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
