spring:
  application:
    name: account-service
server:
  servlet:
    context-path: /${spring.application.name}
  port: 9097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
