spring:
  application:
    name: app-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:9096
        predicates:
          - Path=/user-service/**
      - id: account-service
        uri: http://localhost:9097
        predicates:
          - Path=/account-service/**
      enabled: true
server:
  port: 9095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Spring Actuator Configurations
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

jwt:
  validate: true
  header: authorization
  secret: wcml2yxr-ab34-12rg-34is-wi9ejd749ksi
